stages:
  - build
  - test

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
container_scanning:
  variables:
    CS_DEFAULT_BRANCH_IMAGE: $CI_REGISTRY_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH &&
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - "update focal"
    - "update jammy"

.test-base:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add python3 py3-pip
    - pip3 install click
  script:
    - apk add python3 py3-pip
    - python3 ./tool.py test $IMAGE_DIR
  except:
    - main

.update-base:
  extends: .test-base
  script:
    - python3 ./tool.py update $IMAGE_DIR
  except: []
  only:
    - main

test focal:
  extends: .test-base
  variables:
    IMAGE_DIR: focal

update focal:
  extends: .update-base
  variables:
    IMAGE_DIR: focal

test jammy:
  extends: .test-base
  variables:
    IMAGE_DIR: jammy

update jammy:
  extends: .update-base
  variables:
    IMAGE_DIR: jammy
