stages:
  - build

.build-base:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - docker-compose --version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$IMAGE_NAME" pipenv
    - sh run_test.sh
    - docker push "$IMAGE_NAME"

build:
  extends: .build-base
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

build master:
  extends: .build-base
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE"
  only:
    - master
