stages:
  - build

.test-base:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add python3 py3-pip
    - pip3 install click
  script:
    - apk add python3 py3-pip
    - python3 ./tool.py test $IMAGE_DIR
  except:
    - main

.update-base:
  extends: .test-base
  script:
    - python3 ./tool.py update $IMAGE_DIR
  only:
    - main

test focal:
  extends: .test-base
  variables:
    IMAGE_DIR: focal

update focal:
  extends: .update-base
  variables:
    IMAGE_DIR: focal

test jammy:
  extends: .test-base
  variables:
    IMAGE_DIR: focal

update jammy:
  extends: .update-base
  variables:
    IMAGE_DIR: focal
