stages:
  - build
  - test

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
container_scanning:
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH &&
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH &&
        $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  parallel:
    matrix:
      - IMAGE_TAG: ["focal", "jammy", "lunar"]
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add python3 py3-pip
    - pip3 install click
  script:
    - apk add python3 py3-pip
    - python3 ./tool.py test $IMAGE_TAG

test experimental:
  extends: test
  parallel:
    matrix:
      - IMAGE_TAG: ["mantic"]
  allow_failure: true

update:
  extends: test
  rules:
    - if: $CI_COMMIT_BRANCH &&
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  parallel:
    matrix:
      - IMAGE_TAG: ["focal", "jammy", "lunar"]
  script:
    - python3 ./tool.py update $IMAGE_TAG

update experimental:
  extends: update
  parallel:
    matrix:
      - IMAGE_TAG: ["mantic"]
  allow_failure: true
