stages:
  - build
  - test

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

test:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH &&
        $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  parallel:
    matrix:
      - IMAGE_TAG: ["focal", "jammy", "mantic", "noble"]
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add python3 py3-pip poetry
    - poetry install
  script:
    - poetry run python3 ./tool.py test $IMAGE_TAG

test experimental:
  extends: test
  parallel:
    matrix:
      - IMAGE_TAG: ["alpine"]
  allow_failure: true

update:
  extends: test
  rules:
    - if: $CI_COMMIT_BRANCH &&
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  parallel:
    matrix:
      - IMAGE_TAG: ["focal", "jammy", "mantic", "noble"]
  script:
    - poetry run python3 ./tool.py update $IMAGE_TAG

update experimental:
  extends: update
  parallel:
    matrix:
      - IMAGE_TAG: ["alpine"]
  allow_failure: true
