stages:
  - build

variables:
  HUB_REPO_NAME: musicscience37/pipenv

.build-base:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - docker-compose --version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$IMAGE_NAME" pipenv
    - sh run_test.sh
    - docker push "$IMAGE_NAME"

.build-hub-base:
  extends: .build-base
  after_script:
    - docker login -u "$HUB_USER_NAME" -p "$HUB_ACCESS_TOKEN"
    - docker tag "$IMAGE_NAME" "$HUB_IMAGE_NAME"
    - docker push "$HUB_IMAGE_NAME"

build:
  extends: .build-base
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
    - tags

build tag:
  extends: .build-hub-base
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:$CI_COMMIT_TAG"
  only:
    - tags

build master:
  extends: .build-hub-base
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:latest"
    HUB_IMAGE_NAME: "$HUB_REPO_NAME:latest"
  only:
    - master
